<?php
defined('_JEXEC') or die;
use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
$user=Factory::getApplication()->getIdentity();
?>
<form action="<?php echo Route::_('index.php?option=com_xdecaroanalytics'); ?>" method="post" id="adminForm" name="adminForm">
<div class="container-fluid xdecaro-component"><div class="row g-4"><div class="col-12 col-xl-7"><div class="card"><div class="card-body"><?php echo $this->form->renderFieldset('basic'); ?></div></div></div><div class="col-12 col-xl-5">
<div class="card mb-3"><div class="card-header"><strong><?php echo Text::_('COM_XDECAROANALYTICS_AVAILABLE_PROVIDERS'); ?></strong></div><div class="card-body"><?php if(!$this->providers): ?><div class="alert alert-info mb-0"><?php echo Text::_('COM_XDECAROANALYTICS_NO_PROVIDERS'); ?></div><?php else: foreach($this->providers as $key=>$provider): ?><div class="mb-3"><div><strong><?php echo htmlspecialchars($provider->getLabel(),ENT_QUOTES,'UTF-8'); ?></strong> <code><?php echo htmlspecialchars($key,ENT_QUOTES,'UTF-8'); ?></code></div><div class="small text-muted"><?php foreach($provider->getMetrics() as $metric){echo '<span class="badge bg-info me-1">'.htmlspecialchars((string)($metric['key']??''),ENT_QUOTES,'UTF-8').'</span>';} foreach($provider->getDatasets() as $dataset){echo '<span class="badge bg-secondary me-1">'.htmlspecialchars((string)($dataset['key']??''),ENT_QUOTES,'UTF-8').'</span>';} ?></div></div><?php endforeach; endif; ?></div></div>
<?php if((int)$this->item['id']>0): ?><div class="card"><div class="card-header d-flex justify-content-between align-items-center"><strong><?php echo Text::_('COM_XDECAROANALYTICS_LATEST_RUN'); ?></strong></div><div class="card-body"><?php if(!$this->latestRun): ?><div class="text-muted"><?php echo Text::_('COM_XDECAROANALYTICS_NEVER_RUN'); ?></div><?php else: ?><div class="mb-2"><span class="badge <?php echo $this->latestRun['status']==='success'?'bg-success':'bg-danger'; ?>"><?php echo htmlspecialchars($this->latestRun['status'],ENT_QUOTES,'UTF-8'); ?></span> <?php echo htmlspecialchars((string)$this->latestRun['started_at'],ENT_QUOTES,'UTF-8'); ?> · <?php echo (int)$this->latestRun['row_count']; ?> <?php echo Text::_('COM_XDECAROANALYTICS_ROWS'); ?></div><?php if(!empty($this->latestRun['error_text'])):?><div class="alert alert-danger"><?php echo htmlspecialchars($this->latestRun['error_text'],ENT_QUOTES,'UTF-8'); ?></div><?php endif; ?><?php if(is_array($this->latestRun['result'])):?><pre class="small bg-body-tertiary p-2 rounded" style="max-height:300px;overflow:auto"><?php echo htmlspecialchars(json_encode($this->latestRun['result'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8'); ?></pre><?php endif; ?><?php endif; ?>
<div class="d-flex gap-2 flex-wrap mt-3"><?php if($user->authorise('analytics.run','com_xdecaroanalytics')):?><button class="btn btn-primary" type="button" onclick="Joomla.submitbutton('report.run')"><?php echo Text::_('COM_XDECAROANALYTICS_RUN_REPORT'); ?></button><?php endif; ?><?php if($this->latestRun&&$this->latestRun['status']==='success'&&$user->authorise('analytics.export','com_xdecaroanalytics')):?><button class="btn btn-outline-secondary" type="button" onclick="Joomla.submitbutton('report.export')"><?php echo Text::_('COM_XDECAROANALYTICS_EXPORT_CSV'); ?></button><?php endif; ?></div></div></div><?php endif; ?>
</div></div></div>
<input type="hidden" name="task" value="report.save"><?php echo HTMLHelper::_('form.token'); ?>
</form>
